### ISSUE TITLE
"Некорректный отпечаток сертификата"

### ISSUE THREAD

**Issue by DenisUlyanov** [nkochnev/gis-wcf-sign#1]
Добрый день. Сделал все по статье, установил сертификат, указал его серийный номер в App.config. При попытке запуска приложения получаю исключение 
`System.ArgumentException: "Некорректный отпечаток сертификата"`

Как я понял, проблема в константе CERTIFICATE_THUMBPRINT в классе CryptoConsts. Пробовал заменить на отпечаток своего сертификата, все равно ошибка остается. Как можно это исправить?

**Comment by nkochnev** [comment]
Добрый день!
Мы сталкивались с такой ситуацией. Проблема скорее всего в том, что отпечаток сертификата был скопирован из окна просмотра данных о сертификата. 
Рекомендую полностью стереть значение константы вместе с ковычками и заново перепечатать значение отпечатка.
